add read_array and write_array
unfortunately proving read_array_ok reliably triggers the Type coersion
bug now..  amusingly, they are different error messages from "coqc" and
"coqide"!  the coqide one is much shorter:

  Error: Illegal application:
  The term "fst" of type "forall A B : Type, A * B -> A"
  cannot be applied to the terms
   "mem" : "Set"
   "(valu * (pred * (unit * unit * unit * unit * unit)))%type" : "Type"
   "x" : "(mem * (valu * (pred * (unit * unit * unit * unit * unit))))%type"
  The 2nd term has type "Type" which should be coercible to "Type".

workaround: end the theorem with "Admitted" instead of "Qed", despite
all sub-goals being satisfied.