checkpoint some progress on write_ok
currently, getting some unexpected errors from the [ring] tactic
that propagate past Ltac constructs that are supposed to catch
failures and retry another tactic...

in particular, [cancel'] keeps trying to call [cancel_one], but
if [cancel_one] fails, it should call [delay_one] instead.  here,
we see that a failure in [ring] in [cancel_one] seems to cause the
top-level tactic to error out, without falling back to [delay_one]:

---

In nested Ltac calls to "cancel'", "cancel_one", "pick", "auto with okToUnify",
"Coq.setoid_ring.Ring_tac._35", "F" (bound to PackRing ltac:Ring_gen),
"PackRing", "F" (bound to
fun RNG lH rl => let lemma := get_NormLemma RNG in
                 get_Pre RNG ltac:(); Ring RNG (lemma ring_subst_niter) lH),
"Ring", "OnEquation", "f" (bound to
fun lhs rhs =>
  let mkFV := get_RingFV RNG in
  let mkPol := get_RingMeta RNG in
  let mkHyp := get_RingHypTac RNG in
  let fv := FV_hypo_tac mkFV ltac:(get_Eq RNG) lH in
  let fv := mkFV lhs fv in
  let fv := mkFV rhs fv in
  check_fv fv;
   (let pe1 := mkPol lhs fv in
    let pe2 := mkPol rhs fv in
    let lpe := mkHyp fv lH in
    let vlpe := fresh "hyp_list" in
    let vfv := fresh "fv_list" in
    pose (vlpe := lpe); pose (vfv := fv); apply (lemma vfv vlpe pe1 pe2) || fail "typing error while applying ring";
     [ (let prh := proofHyp_tac lH in
        exact prh) || idtac "can not automatically prove hypothesis :";
        ([>idtac " maybe a left member of a hypothesis is not a monomial".. ])
     | vm_compute; exact eq_refl || fail "not a valid ring equation" ])),
"mkPol" (bound to
fun t fv =>
  let rec mkP t :=
   (let f :=
     (match Cst t with
      | NotConstant =>
          match t with
          | rO => fun _ => constr:Ring_polynom.PEO
          | rI => fun _ => constr:Ring_polynom.PEI
          | radd ?t1 ?t2 =>
              fun _ => let e1 := mkP t1 in
                       let e2 := mkP t2 in
                       constr:(Ring_polynom.PEadd e1 e2)
          | rmul ?t1 ?t2 =>
              fun _ => let e1 := mkP t1 in
                       let e2 := mkP t2 in
                       constr:(Ring_polynom.PEmul e1 e2)
          | rsub ?t1 ?t2 =>
              fun _ => let e1 := mkP t1 in
                       let e2 := mkP t2 in
                       constr:(Ring_polynom.PEsub e1 e2)
          | ropp ?t1 => fun _ => let e1 := mkP t1 in
                                 constr:(Ring_polynom.PEopp e1)
          | rpow ?t1 ?n =>
              match CstPow n with
              | NotConstant => fun _ => let p := Find_at t fv in
                                        constr:(Ring_polynom.PEX C p)
              | ?c => fun _ => let e1 := mkP t1 in
                               constr:(Ring_polynom.PEpow e1 c)
              end
          | _ => fun _ => let p := Find_at t fv in
                          constr:(Ring_polynom.PEX C p)
          end
      | ?c => fun _ => constr:(Ring_polynom.PEc c)
      end) in
    f ltac:()) in
  mkP t), "mkP" (bound to
fun t =>
  let f :=
   (match Cst t with
    | NotConstant =>
        match t with
        | rO => fun _ => constr:Ring_polynom.PEO
        | rI => fun _ => constr:Ring_polynom.PEI
        | radd ?t1 ?t2 =>
            fun _ => let e1 := mkP t1 in
                     let e2 := mkP t2 in
                     constr:(Ring_polynom.PEadd e1 e2)
        | rmul ?t1 ?t2 =>
            fun _ => let e1 := mkP t1 in
                     let e2 := mkP t2 in
                     constr:(Ring_polynom.PEmul e1 e2)
        | rsub ?t1 ?t2 =>
            fun _ => let e1 := mkP t1 in
                     let e2 := mkP t2 in
                     constr:(Ring_polynom.PEsub e1 e2)
        | ropp ?t1 => fun _ => let e1 := mkP t1 in
                               constr:(Ring_polynom.PEopp e1)
        | rpow ?t1 ?n =>
            match CstPow n with
            | NotConstant => fun _ => let p := Find_at t fv in
                                      constr:(Ring_polynom.PEX C p)
            | ?c => fun _ => let e1 := mkP t1 in
                             constr:(Ring_polynom.PEpow e1 c)
            end
        | _ => fun _ => let p := Find_at t fv in
                        constr:(Ring_polynom.PEX C p)
        end
    | ?c => fun _ => constr:(Ring_polynom.PEc c)
    end) in
  f ltac:()), "f" (bound to fun _ => let e1 := mkP t1 in
                                     let e2 := mkP t2 in
                                     constr:(Ring_polynom.PEadd e1 e2)),
"mkP" (bound to
fun t =>
  let f :=
   (match Cst t with
    | NotConstant =>
        match t with
        | rO => fun _ => constr:Ring_polynom.PEO
        | rI => fun _ => constr:Ring_polynom.PEI
        | radd ?t1 ?t2 =>
            fun _ => let e1 := mkP t1 in
                     let e2 := mkP t2 in
                     constr:(Ring_polynom.PEadd e1 e2)
        | rmul ?t1 ?t2 =>
            fun _ => let e1 := mkP t1 in
                     let e2 := mkP t2 in
                     constr:(Ring_polynom.PEmul e1 e2)
        | rsub ?t1 ?t2 =>
            fun _ => let e1 := mkP t1 in
                     let e2 := mkP t2 in
                     constr:(Ring_polynom.PEsub e1 e2)
        | ropp ?t1 => fun _ => let e1 := mkP t1 in
                               constr:(Ring_polynom.PEopp e1)
        | rpow ?t1 ?n =>
            match CstPow n with
            | NotConstant => fun _ => let p := Find_at t fv in
                                      constr:(Ring_polynom.PEX C p)
            | ?c => fun _ => let e1 := mkP t1 in
                             constr:(Ring_polynom.PEpow e1 c)
            end
        | _ => fun _ => let p := Find_at t fv in
                        constr:(Ring_polynom.PEX C p)
        end
    | ?c => fun _ => constr:(Ring_polynom.PEc c)
    end) in
  f ltac:()), "f" (bound to fun _ => let e1 := mkP t1 in
                                     let e2 := mkP t2 in
                                     constr:(Ring_polynom.PEmul e1 e2)),
"mkP" (bound to
fun t =>
  let f :=
   (match Cst t with
    | NotConstant =>
        match t with
        | rO => fun _ => constr:Ring_polynom.PEO
        | rI => fun _ => constr:Ring_polynom.PEI
        | radd ?t1 ?t2 =>
            fun _ => let e1 := mkP t1 in
                     let e2 := mkP t2 in
                     constr:(Ring_polynom.PEadd e1 e2)
        | rmul ?t1 ?t2 =>
            fun _ => let e1 := mkP t1 in
                     let e2 := mkP t2 in
                     constr:(Ring_polynom.PEmul e1 e2)
        | rsub ?t1 ?t2 =>
            fun _ => let e1 := mkP t1 in
                     let e2 := mkP t2 in
                     constr:(Ring_polynom.PEsub e1 e2)
        | ropp ?t1 => fun _ => let e1 := mkP t1 in
                               constr:(Ring_polynom.PEopp e1)
        | rpow ?t1 ?n =>
            match CstPow n with
            | NotConstant => fun _ => let p := Find_at t fv in
                                      constr:(Ring_polynom.PEX C p)
            | ?c => fun _ => let e1 := mkP t1 in
                             constr:(Ring_polynom.PEpow e1 c)
            end
        | _ => fun _ => let p := Find_at t fv in
                        constr:(Ring_polynom.PEX C p)
        end
    | ?c => fun _ => constr:(Ring_polynom.PEc c)
    end) in
  f ltac:()), "f" (bound to fun _ => let p := Find_at t fv in
                                     constr:(Ring_polynom.PEX C p)),
"Find_at" and "find" (bound to
fun n l =>
  match l with
  | nil => fail 100 "anomaly: Find_at"
  | a :: _ => eval compute in n
  | _ :: ?l => find (Pos.succ n) l
  end), last call failed.
Error: Tactic failure: anomaly: Find_at (level 87).