try to fix the proofs for programs returning any [Type] instead of [Set]
still stuck on a universe inconsistency that i don't know how to fix
(which is the original reason we were returning [Set] instead of [Type]):

  % make proof
  ...
  "coqc"  -q  -R "coqproof" Fscq   coqproof/BasicProg
  Identifier 'If' now a keyword
  File "./coqproof/BasicProg.v", line 193, characters 0-4:
  Error: Illegal application:
  The term "fun A A0 : Type => A -> A0" of type "Type -> Type -> Type"
  cannot be applied to the terms
   "L" : "Type"
   "prog T" : "Type"
  The 2nd term has type "Type@{max(Set, Fscq.BasicProg.80)}"
  which should be coercible to "Type@{Fscq.BasicProg.227}".